name: fnx_profiler
description: Imperative profiler for Dart applications.
version: 0.9.2
author: Tomáš Zvěřina <tomucha@gmail.com>
homepage: https://github.com/fnx-io/fnx_profiler

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
